### ISSUE TITLE
Websocket Data Not Updating 

### ISSUE THREAD

**Issue by kalilinux-png** [AsthaTech/jsvortex#3]
Hi @brisingr123  when I connected WebSocket I was getting incorrect data and the WebSocket was also not sending the updated price
after some time interval, I have attached the screenshot below of the code that I used and the output that I was getting please take a look at the last_traded_time and the Windows time also
![image](https://github.com/AsthaTech/jsvortex/assets/69741516/efbdb5f6-e912-4e4e-8c6e-a39afd4d4f94)

Thanks 
Shubham Yadav

**Comment by brisingr123** [comment]
Can you check now ?

**Comment by kalilinux-png** [comment]
> Can you check now ?

yes @brisingr123 it started working now what was the issue, please let me know
