### ISSUE TITLE
Cors-Error for OrderBook

### ISSUE THREAD

**Issue by kalilinux-png** [AsthaTech/jsvortex#5]
![image](https://github.com/AsthaTech/jsvortex/assets/69741516/601c0160-2992-4d32-a1c1-cf082917b576)

Hi @brisingr123 👋 
facing the same cors-error for order book also

**Comment by brisingr123** [comment]
Check now and let me know

**Comment by kalilinux-png** [comment]
> Check now and let me know

Yes this endpoint is working but quote endpoint is still giving the cors error
