### ISSUE TITLE
Pnl Calculation Issue

### ISSUE THREAD

**Issue by kalilinux-png** [AsthaTech/jsvortex#6]
@brisingr123  To Calculate the Pnl I Used the method that was shown in the documentation but this method gave incorrect results 

`
let positionData  = {"exchange":"MCX_FO","symbol":"CRUDEOIL","expiry_date":"2023-08-17","option_type":"CE","token":257369,"product":"INTRADAY","quantity":1,"overnight_buy_value":0,"overnight_sell_value":0,"overnight_average_price":0,"lot_size":100,"multiplier":100,"average_price":17,"value":-1700,"buy_value":3430,"sell_value":1730,"buy_quantity":2,"sell_quantity":1,"buy_price":17.15,"sell_price":17.3}

let ptype = "Long"

let ltp = 19

 if (ptype == "Long") {
    // when buy position is open
    // Gain = (last_trade_price * quantity * lot_size * multiplier +overnight_sell_value ) - overnight_buy_value
    let cpnl = (ltp * positionData.quantity  * positionData.lot_size * positionData.multiplier + positionData.overnight_sell_value) - positionData.overnight_buy_value
    console.log("cpnl for long position", cpnl) }

`

**Comment by brisingr123** [comment]
@hmtp140789 can you please help with mcx pnl calculation

**Comment by hmtp140789** [comment]
Hi @kalilinux-png
Please confirm that you are using "net" array for the calculation, not the "day" array.

**Comment by kalilinux-png** [comment]
> Hi @kalilinux-png Please confirm that you are using "net" array for the calculation, not the "day" array.

@hmtp140789  I am Using Day Array as mentioned in the docs for calculation for Today's Gain

**Comment by hmtp140789** [comment]
@kalilinux-png For today's gain replace "overnight_sell_value" with "sell_value" and "overnight_buy_value" with "buy_value".
Alternatively, you can use the below formula
todayGain =  positionData.value +  positionData.quantity *  positionData.multiplier * lastTradePrice);

**Comment by kalilinux-png** [comment]
> @kalilinux-png For today's gain replace "overnight_sell_value" with "sell_value" and "overnight_buy_value" with "buy_value". Alternatively, you can use the below formula todayGain = positionData.value + ( positionData.quantity * positionData.multiplier * lastTradePrice);

ok Sure @hmtp140789 I will try this during the live market and will let you know 
Is this formula valid for all exchanges like CUR and NFO 
and also please update this in the documentation 

Thanks

**Comment by hmtp140789** [comment]
Hi @kalilinux-png we will update the documentation for better clarity.
The general formula for today's gain is below

todayGain = positionData.value + ( netQty * lastTradePrice);

however the positionData.quantity changes according to the exchange
    if (exchange is NSE_FO) {
       netQty = positionData.quantity;
    } else if (exchange is MCX_FO) {
      netQty = positionData.quantity * positionData.multiplier;
    } else {
      netQty =  positionData.quantity * positionData. lot_size;
    }
    
Let us know if this clarifies your doubt. We are always available to support your development and growth, feel free to reach out to us for any concerns not restricted to technical ones.

**Comment by kalilinux-png** [comment]
> 

Yes Surely @hmtp140789  👍🏻 😁

**Comment by kalilinux-png** [comment]
> resolved @kalilinux-png ?

Yes @brisingr123  This issue is resolved 
Thanks a lot 😃
